name: Bundle Analysis

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and analyze bundle
        run: npm run build:bundle-analyze

      - name: Analyze bundle with source-map-explorer
        run: npm run analyze

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-${{ github.sha }}
          path: |
            .next/analyze/
            .next/static/
          retention-days: 7

      - name: Comment bundle size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Get build info
            const buildManifest = JSON.parse(fs.readFileSync('.next/build-manifest.json', 'utf8'));
            const appBuildManifest = JSON.parse(fs.readFileSync('.next/app-build-manifest.json', 'utf8'));

            // Calculate total bundle size
            let totalSize = 0;
            const bundleInfo = [];

            // Get static chunk sizes
            for (const [page, chunks] of Object.entries(buildManifest.pages)) {
              for (const chunk of chunks) {
                try {
                  const chunkPath = path.join('.next', chunk);
                  const stats = fs.statSync(chunkPath);
                  totalSize += stats.size;
                  bundleInfo.push(`${chunk}: ${(stats.size / 1024).toFixed(2)} KB`);
                } catch (e) {
                  // File might not exist, skip
                }
              }
            }

            const comment = `## 📦 Bundle Analysis

            **Total Bundle Size**: ${(totalSize / 1024 / 1024).toFixed(2)} MB

            <details>
            <summary>View detailed breakdown</summary>

            ${bundleInfo.slice(0, 20).map(info => `- ${info}`).join('\n')}

            ${bundleInfo.length > 20 ? `\n... and ${bundleInfo.length - 20} more files` : ''}

            </details>

            > Bundle analysis artifacts are available in the workflow run.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });